### ISSUE TITLE
Include fonts in inst/

### ISSUE THREAD

**Issue by seasmith** [moldach/vapoRwave#1]
Including the fonts in `inst/` would make these fonts accessible to R code via `system.file()` -- allowing them to be be registered and loaded via `extrafont` within the `vapoRwave` package.

The `DESCRIPTION` file would need to reflect the font authors, copyright holders, etc.  Most of the fonts seem to not have any license restrictions prohibiting this kind of distribution.

**Comment by moldach** [comment]
Thank you for the useful issue @seasmith I'll be sure to address this.

**Comment by mrbuche** [comment]
I'm also having some trouble getting the fonts to work, even when doing this. Has anyone had any luck? Could we make a Docker image?

**Comment by moldach** [comment]
Hello @mrbuche,

Apologies for the delayed response, and thank you for your patience 😊  Could you please specify the operating system you are using?

I've implemented a `zzz.R` file that streamlines font installation for Ubuntu users. For Windows users, I've documented additional manual steps in the README. Please note that the MacOS compatibility is yet to be tested 🚀

I appreciate your suggestion, and I'm considering creating a Docker image in the near future to enhance accessibility. Your feedback is valuable, and I'm committed to improving the user experience :wheelchair: 

Thank you again for bringing this to my attention @seasmith :heart:

**Comment by mrbuche** [comment]
@moldach thank you so much for your response!

I was using WSL in Windows but since then I have an actual Ubuntu OS. Tried it today, works great! I bet the extra stuff you added lately works for Windows.
